ToDoGardenTimePicker 추가
ToDo-Garden/ToDo-Garden pull request #162
Opened 2024-05-20 08:50 UTC by HG-SONG

## 💡 관련 이슈
- closed: #161 
## 🎉 변경 사항
- ToDoGardenTimePicker 를 추가합니다.

## 📌 PR Point

<img width="602" alt="스크린샷 2024-05-20 오후 5 45 24" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/fa78363a-b7ab-464a-8892-acf49e97242a">
<img width="485" alt="스크린샷 2024-05-20 오후 5 51 13" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/533c6706-f588-4fc5-bcc7-361363bb4506">

SettingTimeView 내에서 사용될 ToDoGardenTimePicker입니다.
3가지 케이스를 커버가능하며, 외부에서 선택된 시간에 대해 접근할 수 있도록 만들었습니다. 

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-05-20 12:24 UTC, GangWoon requested changes

2024-05-20 12:24 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    return CGSize(width: width, height: height)
Width, height를 갖고 있는 상태에서 cgsize를 생성하는 방법보단 configuration 자체에서 cgsize를 갖고 있게 되면 위와 같은 코드가 제거될 거 같습니다.

어떻게 생각하시나요??

2024-05-20 12:24 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    let calendar = Calendar.current
날짜 생성과 관련해서는 테스트 코드를 작성하는 방향이 좋을 거 같아요.
해당 뷰 입장에서 위와 같은 계산을 해주는 중간 레이어를 두면 뷰를 테스트 하지 않아도 해당 로직에 대해서 테스트하기 적합해 보이고요.

혹시 제말이 이해하기 어려우시다면 예시 코드나 페어프로그래밍을 하는것도 좋을 거 같습니다 :)

2024-05-20 12:24 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    self.subviews[Int.zero].backgroundColor = UIColor.clear
Subview가 아닌 다른 특정한 대상으로 명시할 순 없을까요?

처음 코드를 확인했을 때 어떤 뷰인지 햇갈리게 느껴집니다.

2024-05-20 12:24 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    if let leading = leading {
아래에서 얘기할 내용은 취향적인 부분으로 느껴지는 부분 같습니다.

Optional로 분기를 하는 방향이 아닌, 외부에서 컨스트레인트를 주입 받는 방향은 어떠신가요?
컬렉션 타입을 부분적으로 적용하면 간결한 코드로 유지할 수 있을 거 같습니다.

아래는 예시 코드에 대한 방향성입니다.

```
setupUnitLabel(with: "hello", [.leading, .trailing])

func setupUnitLabel(....) {
constraints.forEach { ....}
````

2024-05-20 12:24 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +  func applyTextAttributes() -> NSAttributedString {
해당 메소드는 앱 전체적으로 사용될 가능성이 큰 메소드인거 같아요.

내일 회의때 다 같이 얘기해서 확장하는 곳을 만들어도 좋을 거 같습니다.

2024-05-21 08:58 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    return CGSize(width: width, height: height)
아래 커밋에서 반영하였습니다. 
> [5c2711a](https://github.com/ToDo-Garden/ToDo-Garden/pull/162/commits/5c2711a35b1bfdd2de36b9b206baa5463c2c135e)

2024-05-21 08:58 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    let calendar = Calendar.current
오 이런...  강운의견 동의합니다. 뷰에서 해당 로직을 가지고 있는건 부적합해보입니다. 이후 VIP사이클의 Interactor 단에서 해당 로직을 수행해주는게 좋을 것 같습니다. 
selectedTime() 메서드는 제거하였습니다. 

> [c8665b2](https://github.com/ToDo-Garden/ToDo-Garden/pull/162/commits/c8665b2477733e7267c3b2fd0dcbca30f8bc9beb)

2024-05-21 08:58 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    self.subviews[Int.zero].backgroundColor = UIColor.clear
아예 메서드로 분리시켜 처리하는 방식으로 바꾸어 보았습니다. 

> [351c7a7](https://github.com/ToDo-Garden/ToDo-Garden/pull/162/commits/351c7a7e38ae03d1862e5d307104fc5c8c5bcb36)

2024-05-21 08:58 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    if let leading = leading {
configuration 에서 제약의 case를 주입받고 해당 case에 따라 레이아웃 제약을 걸어주는 방식으로 바꾸어 보았습니다. 강운이 제시해주신 방향성을 기준으로 수정을 해보았는데 제시해주신 방향따라 잘 간건지 궁금하네요 ㅋㅋ 
> [2f26a29](https://github.com/ToDo-Garden/ToDo-Garden/pull/162/commits/2f26a292940dd477b1f30b2bf3640d7cd2637823)

2024-05-21 08:58 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +  func applyTextAttributes() -> NSAttributedString {
요놈은 따로 이슈를 파서 관련 변경사항 한번에 수정하도록 하겠습니다.

2024-05-21 10:56 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    if let leading = leading {
유사한 방향같습니다 :)
View를 생성하기전에 정보를 받아야하기 때문에 중간 레이어가 필요하긴 합니다 :)

2024-05-21 10:57 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    self.subviews[Int.zero].backgroundColor = UIColor.clear
프로퍼티로 잡아두는것도 명시적일 거 같지만 위와 같이 메소드를 분리하는 방식으로 해도 명시적으로 확인할 수 있을 거 같습니다 :)

2024-05-21 10:59 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    let calendar = Calendar.current
@noah0316 @wood0203 
모든 구조를 VIP 안에 가두는건 저는 조금 부정적으로 생각하고 있습니다.
다른 분들 의견도 궁금해서 멘션을 겁니다.

우리가 직접적으로 관리해야하는 상태는 VIP 구조내에서 관리를 해야한다고 생각하지만 예를 들어서 Button의 isSelected와 같은 뷰에 연결된 상태값은 뷰 내부에서 관리하는 형태로 가고 싶은데 다른 분들의 의견도 달아주시면 감사하겠습니다 :)

2024-05-21 11:00 UTC, GangWoon approved these changes

2024-05-21 11:01 UTC, GangWoon commented
로직 관련된 코드는 추후 다른 PR로 수정이 되도 괜찮을 거 같습니다 :)
해당 PR은 머지하셔도 좋을 거 같습니다. 하지만 해당 PR이 머지되더라도 다른 분들의 의견은 달아주셨으면 좋겠습니다.

2024-05-21 14:52 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    let calendar = Calendar.current
@GangWoon 
먼저 뷰에 직접적으로 연결된 상태값을 다른 곳에서 관리해야할 경우 상태의 동기화 과정에서 오는 복잡도가 늘어나는게 가장 큰 비용이 될 것 같습니다.

저는 말씀주신 중간 레이어의 예시가 궁금하네요 👀
뷰 내부에서 관리하는 형태와 중간 레이어를 둔다는 것의 차이가 궁금합니다.

2024-05-21 16:06 UTC, GangWoon reviewed
@HG-SONG 
1. 예시 코드 커밋은 사람들의 이해도를 높이기 위해 작성된 코드입니다. 해당 코드가 저희 프로젝트에 추가되지 않았으면 좋겠습니다.
예시 코드는 커밋은 마지막에 해당 PR이 닫힐 때 날리고 머지 부탁드리겠습니다 :)

2.추가로 빌드가 불가능한 상태인거 같습니다 :) 확인 부탁드리겠습니다.

2024-05-21 16:06 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    dateBuilder: DateBuilder = .live
@noah0316 
같이 중간 레이어를 둔다는 표현은 위 코드와 같습니다.
뷰 내부에서 로직을 계산하는 것이 아닌 외부로 따로 계산하는 객체를 두는걸 뜻했습니다.

경우에 따라서 상태값을 갖는 상황도 발생하겠지만, 순수함수를 제작함으로 써 사이드 이펙트를 줄이고, 뷰 로직에 영향을 받지 않는 테스트 환경을 만드는게 주된 목적입니다.

2024-05-21 16:06 UTC, GangWoon commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +  }
테스트를할 때, 여러가지 상황에 대해서 테스트가 필요하다면 위와 같은 방법으로 인터페이스를 수정해서 원하는 결과값을 나오게 만들 수도 있습니다.

2024-05-22 04:41 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    let calendar = Calendar.current
@GangWoon 저도 뷰와 관련된 상태는 뷰가 가지는 것에 동의합니다
하지만 중간레이어에 대한 개념이 명확하게 이해되지 않아 내일 스크럼때 다같이 이야기 해보면 좋을 것 같습니다 🙂

2024-05-23 05:10 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenTimePicker.swift
> +    dateBuilder: DateBuilder = .live
> 예를 들어서 Button의 isSelected와 같은 뷰에 연결된 상태값은 뷰 내부에서 관리하는 형태로 가고 싶은데 다른 분들의 의견도 달아주시면 감사하겠습니다 :)

회의중에 댓글 남깁니다! 이 코멘트였습니다 :)

2024-05-30 08:28 UTC, merged