RepeatOtherDaysView 추가
ToDo-Garden/ToDo-Garden pull request #188
Opened 2024-05-30 06:24 UTC by HG-SONG

## 💡 관련 이슈
- closed: #171 
## 🎉 변경 사항
- RepeatOtherDaysView 추가 
- RepeatOtherDaysViewModel 추가 

## 📌 PR Point

### 실행화면
![Simulator Screen Recording - iPhone 15 - 2024-05-30 at 14 51 30](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/e3123503-9ed9-4c61-a019-167916458397)

- 실제로는 자연스러운 애니메이션이 적용되어 있습니다. 

### 기능설명
![스크린샷 2024-05-30 오후 3 06 55](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/307a30f2-08cb-4d46-b259-f77952924758)
![스크린샷 2024-05-30 오후 3 07 04](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/35886ff1-7fb2-4d45-a81b-bdd0fd07e144)

- 아래와 같이 사용가능합니다. 
```swift
let repeatView = RepeatOtherDaysView(startDate: "2323.23.23", endDate: "9999.99.99") // addSubview이후 x,y 위치 지정 요망

repeatView.dateButtonSet.addAction(someUIAction, for: .touchUpInside) // 모듈 외부에서 시간지정 버튼에대한 액션 할당

repeatView.updateDate(startDate: "9999.99.99", endDate: "0000.00.00") // 모듈 외부에서 날짜 변경
```

### 뷰 바인딩과 테스터블 
RepeatOtherDaysViewModel의 존재 이유는 뷰 바인딩과 테스트코드 작성시 용이함을 목적으로 만들었습니다. 

- 각 버튼의 상태에 따라 다른 요소들의 상태 변경이 많음. -> 테스트코드를 작성해야 할 필요성
- 가변할 수 있는 상태값들을 ViewModel에 모아놓았습니다. 
- 해당 상태들은 `private(set)`을 적용하여 외부에서 직접 접근하여 변경될 수 없고, 항상 RepeatOtherDaysViewModel 내부의 메서드를 거쳐 변경(set)됩니다. 
- RepeatOtherDaysViewModel의 메소드를 실행시키고, 이후 각 상태값을 확인하는 방식의 테스트코드를 작성할 수 있습니다. 

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-06-04 09:33 UTC, wood0203 requested changes
확인했습니다 
다음 리뷰들을 확인해주세요!

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +      viewModel.isSelected.value = newValue
`p2`
self 키워드가 누락되어 있습니다

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +    self.divider = UIView()
`p2`
UIView 객체이므로 네이밍에 suffix로 View를 붙여주면 더 명확할거 같습니다

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +  }
`p2`
UIAction을 정의하는 로직을 분리하면 더 가독성이 좋을 것 같습니다
``` Swift
let action = UIAction { [weak self] _ in
  // ...
}
self.ringToggleButton.addAction(action, for: UIControl.Event.touchUpInside)
```

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +      with: []
`p1`
Row 초기화시 with 파라미터에 빈 배열을 입력하는 대신
다음 생성자로 수정하면 좋을 것 같아요

https://github.com/ToDo-Garden/ToDo-Garden/blob/5f2a6ed822e101d49c34c047feaa067830575179/ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/Styled/Row/Row.swift#L26-L30

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysViewModel.swift
> +    dateFormatter.dateFormat = "yyyy.MM.dd"
`p1`
StringLiteral 값은 Constant로 옮기면 좋을 것 같습니다

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +#endif
`p1`
매일을 선택했을 때, 다른날도 할래요 Label의 색상이 Figma 디자인과 다른 것 같습니다!
1. 레이블의 TitleColor
2. DateButton BackgroundColor

|Figma 디자인|PR|
|--|--|
|<img width="296" alt="스크린샷 2024-06-04 17 12 56" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/8c4458ae-cc59-4f7c-bebd-a74389c30e5b">|<img width="296" alt="스크린샷 2024-06-04 18 01 55" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/cc3b0380-babb-45c3-bc79-4c1c9e314771">|

- 코멘트를 남길 적당한 부분이 보이질 않아 해당 라인에 작성했습니다

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysViewModel.swift
> +      listener?(value)
`p2`
self 키워드가 누락되어 있어요

2024-06-04 09:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysViewModel.swift
> +class Observable<T> {
`p1`
상속될 가능성이 없으므로 final 키워드를 붙여주면 좋을 것 같습니다

2024-06-04 09:39 UTC, wood0203 commented
@HG-SONG 
리뷰에 빠진 부분이 있어 추가적으로 코멘트를 남깁니다.
ViewController를 생성하고, 해당 컴포넌트를 추가하여 실행했을 때
빌드에는 문제가 없지만, Auto Layout이 깨지는 현상이 발생하네요

- Figma 디자인에 맞게 Width를 315로 설정하였습니다.
- 아래 링크는 해당 상황이 발생할 때 사용했던 코드입니다.

https://gist.github.com/wood0203/8c749e726c4d3a3853702144e9186e61

2024-06-08 09:07 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +      viewModel.isSelected.value = newValue
반영 완료 
> [9b16db8](https://github.com/ToDo-Garden/ToDo-Garden/pull/188/commits/9b16db858668dab20d7fd2aa5aa25bac8fc1de1e)

2024-06-08 09:07 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +    self.divider = UIView()
반영 완료 
> [97c292f](https://github.com/ToDo-Garden/ToDo-Garden/pull/188/commits/97c292f779826852a48ec4042b0559208fe7ade1)

2024-06-08 09:07 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +#endif
해당 사항은 #185 에서 수정되었습니다.

2024-06-08 09:07 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysViewModel.swift
> +      listener?(value)
반영 완료 
> [9b16db8](https://github.com/ToDo-Garden/ToDo-Garden/pull/188/commits/9b16db858668dab20d7fd2aa5aa25bac8fc1de1e)

2024-06-08 09:07 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysViewModel.swift
> +class Observable<T> {
반영완료
> [9b16db8](https://github.com/ToDo-Garden/ToDo-Garden/pull/188/commits/9b16db858668dab20d7fd2aa5aa25bac8fc1de1e)

2024-06-08 09:09 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +      with: []
추가파라미터가 없는 생성자와 추가파라미터가 있는 생성자는 레이아웃세팅 로직이 다릅니다. 

디자인 요구사항을 맞추기 위해서는 제가 사용하는 Row에선 추가파라미터가 있는 생성자를 사용해야합니다.

2024-06-08 09:09 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysView.swift
> +  }
반영 완료 
> [02ff41d](https://github.com/ToDo-Garden/ToDo-Garden/pull/188/commits/02ff41d34e4e80c0ef6b22fa1d1ee95c0607b276)

2024-06-08 09:11 UTC, HG-SONG commented
> 리뷰에 빠진 부분이 있어 추가적으로 코멘트를 남깁니다. ViewController를 생성하고, 해당 컴포넌트를 추가하여 실행했을 때 빌드에는 문제가 없지만, Auto Layout이 깨지는 현상이 발생하네요
> 
> * Figma 디자인에 맞게 Width를 315로 설정하였습니다.
> * 아래 링크는 해당 상황이 발생할 때 사용했던 코드입니다.

@wood0203 
문제 확인하였으며, 솔루션을 찾은 상태입니다. 다만 현재 PR이후에 머지된 사항들이 적용이된 develop 브랜치에서 테스트해보고 수정을 하고싶습니다. 
(#185 와 같은 사항이 적용된 상태로 테스트하고 싶음)
일단 해당 PR은 빌드에는 문제가 없으므로 머지하고, 이후 수정PR을 다시 파겠습니다.

2024-06-08 09:13 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysViewModel.swift
> +    dateFormatter.dateFormat = "yyyy.MM.dd"
어차피 수정 PR에서 Constant파일을 건드려야 할 것 같아서, 이부분도 수정PR에서 수정하고 싶습니다.

2024-06-08 10:02 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/RepeatOtherDaysViewModel.swift
> +    dateFormatter.dateFormat = "yyyy.MM.dd"
> 어차피 수정 PR에서 Constant파일을 건드려야 할 것 같아서, 이부분도 수정PR에서 수정하고 싶습니다.

확인했습니다

2024-06-08 10:31 UTC, wood0203 approved these changes

2024-06-10 02:16 UTC, merged