CalendarView Constant 추가
ToDo-Garden/ToDo-Garden pull request #193
Opened 2024-05-30 17:34 UTC by wood0203

## 💡 관련 이슈
- closed: #192 

## 🎉 변경 사항
- CalendarView에 필요한 Constant를 추가하였습니다.

## 📌 PR Point
- 레이아웃이 필요한 서브뷰들에 대한 이해을 돕기 위해 이미지를 첨부하였습니다
<img width="400" alt="스크린샷 2024-05-31 02 27 37" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/4ba88c58-c2d5-4ff9-8637-44e849fc2a6a">

- dateFormat은 Cell과 MonthLabel에 표시할 날짜의 텍스트를 생성하는데 사용합니다.

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-06-03 07:08 UTC, noah0316 requested changes
확인했습니다 :)

2024-06-03 07:08 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+CalendarView.swift
> +  public static let cellIdentifier = "CalendarCollectionViewCell"
p1;

해당 identifier는 아래의 리뷰와 관련하여 사용하지 않아도 될 것 같습니다 :)
리뷰: https://github.com/ToDo-Garden/ToDo-Garden/pull/200#discussion_r1623799431

2024-06-04 05:04 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+CalendarView.swift
> +  public static let cellIdentifier = "CalendarCollectionViewCell"
> p1;
> 
> 해당 identifier는 아래의 리뷰와 관련하여 사용하지 않아도 될 것 같습니다 :) 리뷰: [#200 (comment)](https://github.com/ToDo-Garden/ToDo-Garden/pull/200#discussion_r1623799431)

@noah0316 
다음 커밋에서 반영하였습니다!
https://github.com/ToDo-Garden/ToDo-Garden/pull/193/commits/3038650afe2bc7c391f116665f751cc48cfc86fd

2024-06-05 07:27 UTC, noah0316 approved these changes
고생하셨습니다 :)

2024-06-05 07:29 UTC, merged