CalendarView 추가
ToDo-Garden/ToDo-Garden pull request #200
Opened 2024-05-31 13:27 UTC by wood0203

## 💡 관련 이슈
- closed: #198

## 🎉 변경 사항
- ToDoGardenUIComponent타겟에 CalendarView를 추가하였습니다.
- 날짜별 투두 목록 조회 및 투두 반복 범위 설정에 사용됩니다. 

## 📌 PR Point
### 1. 스크롤 액션
- 뒤로가기/ 앞으로가기 버튼을 이용하거나 사용자가 Drag 함으로써 스크롤이 가능합니다.
- 사용자가 맨 왼쪽 또는 맨 오른쪽으로 스크롤하면 날짜를 갱신합니다. 
- 스크롤한 날짜에 맞게 년/월 텍스트와 높이를 동적으로 변경합니다. 
- [관련 기술서](https://www.notion.so/49bf319db5a846689c9dbdc6980f939c?pvs=4#ae6b1db2f39c449fbdb984374944b29e)

![2024-05-31 22 18 31 resize](https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/a6913b96-d44c-4592-8f34-9099324c92dd)

### 2. 날짜 선택
- 사용자가 날짜를 선택하면 선택 표시로 변경합니다.
- 만약 선택한 날짜가 이전달 또는 다음달에 속하는 경우, 자동으로 스크롤합니다. 
- [관련 기술서](https://www.notion.so/49bf319db5a846689c9dbdc6980f939c?pvs=4#0be512536c994999bdeeb1afa7d83733)

![셀 선택](https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/44ef660c-7e24-46d9-934d-29153be7a15e)

### File Changed가 3개..?
- CalendarCollectionViewCell 파일은 따로 PR을 보낼까 고민했지만, 컴파일 에러를 발생시켜 PR에 포함시켰습니다.

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-06-03 05:53 UTC, noah0316 requested changes
고생하셨습니다:) 리뷰 확인해주시면 감사하겠습니다!

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +      collectionViewModel: self.model.collectionView
p1;

`self` 인스턴스가 초기화되기전에 `self` 키워드가 사용되고 있는데 컴파일이 되나요?
제가 해당 브랜치로 가서 컴파일을 해본결과 컴파일이 되지 않는데, 한번 확인해주실 수 있을까요?

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +  private var weekdaySymbolStackView: UIStackView
p1;

모든 프로퍼티가 var로 선언되어있는데, 모두 다 변경될 여지가 있는 프로퍼티들인가요?
몇개의 프로퍼티는 아래의 코드에서 변경되는 부분이 없는 것 같아서요:)

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +  private var collectionView: UICollectionView
p2;

조금 더 명확한 변수명이면 좋을 것 같습니다:)

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +  func didScrolled()
p1;

did가 이미 과거 시제이기 때문에 didScroll이 맞는 표현 같습니다 :)

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarCollectionViewCell.swift
> +}
p1;

`ReusableIdentifier` 프로토콜 구현부 7번 라인부터 프로토콜 확장이 구현되어있어 identifier를 따로 정의해주지 않아도 됩니다 :)

```swift
extension ReusableIdentifier {
  public static var identifier: String {
    String(describing: self)
  }
}
```

(혹시나 해서 다른 미리 정의된 identifier와 다른 identifier를 사용하시려고 했나해서 https://github.com/ToDo-Garden/ToDo-Garden/pull/193 해당 PR을 확인하고 왔는데, 동일한 identifier를 사용하고 계셔서 남깁니다 :) )

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView+setupCollectionView.swift
> +    }
p2;

해당 클로져가 정의된 이유를 알 수 있을까요? 👀

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView+setupCollectionView.swift
> +    }
따로 정의된 부분이 없어서요!

2024-06-03 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +    self.calendarViewDelegate.calendarScrollSender = self
p1;

기술서와 현재 정의된 코드를 보면 `CalendarView`와 `CalendarViewDelegate` 객체가 서로 강하게 참조하고 있어 참조 사이클이 형성되어 있습니다 이 부분에 대해서도 코드를 실행해본 결과 deinit이 잘안되는 것 같은데 이 부분도 확인해주실 수 있을까요?

<img width="579" alt="Screenshot 2024-06-03 at 2 35 44 PM" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/63908856/e9bb2835-9d56-49a5-9472-cd446a4eacdf">

2024-06-03 07:05 UTC, HG-SONG commented
@wood0203 
안녕하세요 QA맨입니다. 몇가지 문제점을 발견하였습니다. 

`p1`

### I. 덜컹

![Simulator Screen Recording - iPhone 15 - 2024-06-03 at 16 02 59](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/f72f611a-edff-4cec-9bde-91a53f32362d)

- 프리뷰에서 단독으로 쓰일 때는 자연스럽게 애니메이션이 되는것으로 보이나, superview가 생기면 애니메이션시 덜컹거리는 현상 

### II. 3개월 단위 끊김 현상 
월 이동을 할 때, 매 3회마다 부자연스러운 끊김현상이 있습니다. 

### III. 다음달 / 이전달 날짜 터치 후, 현재 달로 돌아왔을 때 날짜 색상

![Simulator Screen Recording - iPhone 15 - 2024-06-03 at 15 55 37](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/e3fd158f-e39b-4d6b-bcf2-d95371bc31da)

- cell이 뒤틀려 있는 건 GIF상에서만 그런거고 실제로는 cell이 뒤틀려 있진 않습니다. 
- 8월 3일을 터치하고, 다시 7월도 돌아왔을때 , 7월의 달력에 표시된 8월 3일이 GreenDark색상입니다. 

### IV. 마지막 줄 짤림현상 

![스크린샷 2024-06-03 오후 4 02 00](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/fc4889a0-f07d-4211-b47a-7e977dd728c4)

![스크린샷 2024-06-03 오후 4 04 39](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/b0321a2e-60f8-4e41-9155-2f1b8b26acd8)
- 아래쪽 공간이 부족한것 같습니다.

2024-06-06 02:19 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +      collectionViewModel: self.model.collectionView
> p1;
> 
> `self` 인스턴스가 초기화되기전에 `self` 키워드가 사용되고 있는데 컴파일이 되나요? 제가 해당 브랜치로 가서 컴파일을 해본결과 컴파일이 되지 않는데, 한번 확인해주실 수 있을까요?

@noah0316 
먼저, 컴파일 되지 않는 코드를 올리지 않도록 주의하겠습니다
컴파일될 수 있도록 다음과 같은 조치를 했습니다.
1. develop 브랜치를 merge
  - 별도의 PR에서 머지된 Constant, Delegate 등을 사용할 수 있게 merge 하였습니다.

2. Height 업데이트 애니메이션 로직 삭제
  - 이를 구현하기 위해서는 Delegate에 높이를 계산해서 반환하는 메서드가 필요한데,
   해당 로직이 빠져있어 noah가 괜찮다면 별도의 PR에서 진행해도 괜찮을까요?

해당 변경사항들은 다음 커밋에서 확인하실 수 있습니다.
https://github.com/ToDo-Garden/ToDo-Garden/pull/200/commits/7b6ef80699b7e6c9a3308143d745456ed215659e

2024-06-06 02:21 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +  private var weekdaySymbolStackView: UIStackView
> p1;
> 
> 모든 프로퍼티가 var로 선언되어있는데, 모두 다 변경될 여지가 있는 프로퍼티들인가요? 몇개의 프로퍼티는 아래의 코드에서 변경되는 부분이 없는 것 같아서요:)

다음 커밋에서 반영하였습니다!
https://github.com/ToDo-Garden/ToDo-Garden/pull/200/commits/575bffab0b5ce8b71c8d346b3762f19f4f114411

2024-06-06 02:22 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +  func didScrolled()
> p1;
> 
> did가 이미 과거 시제이기 때문에 didScroll이 맞는 표현 같습니다 :)

다음 커밋에서 반영하였습니다
https://github.com/ToDo-Garden/ToDo-Garden/pull/200/commits/7484574b7c7c1efed3eeacf8471abd017a76ebfd

2024-06-06 02:28 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +  private var collectionView: UICollectionView
> p2;
> 
> 조금 더 명확한 변수명이면 좋을 것 같습니다:)

@noah0316 
다음과 같이 수정하였습니다.
1. backButton -> leftScrollButton
2. forwardButton -> rightScrollButton
3. collectionView -> dateCollectionView
https://github.com/ToDo-Garden/ToDo-Garden/pull/200/commits/6c8df63e4497e6ba908d98f81b89959d7219dbf3

StackView의 네이밍을 구현하면서도 고민을 많이 했었는데,
Apple에서 월, 화, 수 등 날짜 명칭을 [Weekday Symbol](https://developer.apple.com/documentation/foundation/calendar/2293235-weekdaysymbols)로 정의하고 있기에
그대로 가져가는건 어떨까요?
보다 좀더 명확한 네이밍을 원하신다면 수정하도록 하겠습니다!

2024-06-06 02:30 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarCollectionViewCell.swift
> +}
> p1;
> 
> `ReusableIdentifier` 프로토콜 구현부 7번 라인부터 프로토콜 확장이 구현되어있어 identifier를 따로 정의해주지 않아도 됩니다 :)
> 

감사합니다! 제대로 확인하지 못했던 부분이였습니다.
다음 커밋에서 반영하였습니다!
https://github.com/ToDo-Garden/ToDo-Garden/pull/200/commits/7cb74fc416cdd8cfd8f0a0f7f5f47709ca902bd7

2024-06-06 02:53 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView+setupCollectionView.swift
> +    }
> p2;
> 
> 해당 클로져가 정의된 이유를 알 수 있을까요? 👀
> 따로 정의된 부분이 없어서요!

@noah0316
해당 클로저는 CalendarView의 높이가 변경되었을 때, 셀을 담는 ScrollView의 높이도 함께 업데이트하는데 사용됩니다.

해당 클로저를 정의하지 않으면, CalendarView에서 총 6주의 데이터를 보여줘야 하는 경우에 
마지막 주의 셀이 선택되지 않는 버그가 있습니다.
ex) 2025년 3월

이유는 높이를 업데이트 했을 때 셀을 포함하는 ScrollView의 높이가 정확하게 업데이트 되지 않기 때문입니다.
클로저를 정의하지 않았을 때 버그를 스크린 샷으로 남겼습니다.

|버그 발생 달|View HeirArchy|
|--|--|
|![2024-06-06 GIF speed changer](https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/a7aafdc2-4cf3-4cbd-8bc4-fae028949af2)|<img width="500" alt="스크린샷 2024-06-06 11 07 21" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/da27c745-af2e-45e9-a041-7cb695c1ea4a">|


스크린샷을 보시면 UICollectionViewOrthognalScrollView가 CollectionView의 크기와 일치하지 않고 있습니다.
(마지막 주의 날짜를 마우스로 클릭하고 있지만, 셀이 선택되지 않고 있습니다.)
- 결론적으로 해당 클로저는 *셀을 담는 ScrollView를 CollectionView 높이에 맞게 업데이트 해주는 기능*입니다.

2024-06-06 02:57 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +    self.calendarViewDelegate.calendarScrollSender = self
> p1;
> 
> 기술서와 현재 정의된 코드를 보면 `CalendarView`와 `CalendarViewDelegate` 객체가 서로 강하게 참조하고 있어 참조 사이클이 형성되어 있습니다 이 부분에 대해서도 코드를 실행해본 결과 deinit이 잘안되는 것 같은데 이 부분도 확인해주실 수 있을까요?

@noah0316 
생각하지 못 했던 부분인데 감사합니다!!
CalendarViewDelegate의 calendarScrollSender 프로퍼티를 weak으로 정의하여 해결할 예정입니다.
해당 리뷰는 Delegate 객체를 수정해야 되기에 새로운 PR에서 진행하여도 괜찮을까요?

2024-06-06 03:04 UTC, wood0203 commented
> @wood0203 안녕하세요 QA맨입니다. 몇가지 문제점을 발견하였습니다.
> 

@HG-SONG 
컴파일이 되지 않았을텐데 빌드 되도록 해결하고 QA까지 진행해주시어 정말 감사합니다.
해당 문제들을 확인하였으며, Delegate 객체를 수정해야되는 부분들이 있어
새로운 PR에서 진행해도 괜찮을까요?

2024-06-06 05:30 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +  private var collectionView: UICollectionView
21번 라인 collectionView에 대해서만 말씀드렸던건데,이렇게 표시되었군요 ㅜ
반영해주셔서 감사합니다!
말씀주신 방향 좋은 것 같네요👍

2024-06-06 05:59 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView+setupCollectionView.swift
> +    }
예시 사진 감사합니다 :) 덕분에 잘 이해했습니다

2024-06-06 06:00 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +      collectionViewModel: self.model.collectionView
> Height 업데이트 애니메이션 로직 삭제
이를 구현하기 위해서는 Delegate에 높이를 계산해서 반환하는 메서드가 필요한데,
해당 로직이 빠져있어 noah가 괜찮다면 별도의 PR에서 진행해도 괜찮을까요?

네 알겠습니다 :)

2024-06-06 06:01 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +      collectionViewModel: self.model.collectionView
PR 진행 후 멘션 주시면 다시 확인해보겠습니다!! :)

2024-06-06 06:01 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/CalendarView/CalendarView.swift
> +    self.calendarViewDelegate.calendarScrollSender = self
> > p1;
> > 기술서와 현재 정의된 코드를 보면 `CalendarView`와 `CalendarViewDelegate` 객체가 서로 강하게 참조하고 있어 참조 사이클이 형성되어 있습니다 이 부분에 대해서도 코드를 실행해본 결과 deinit이 잘안되는 것 같은데 이 부분도 확인해주실 수 있을까요?
> 
> @noah0316 생각하지 못 했던 부분인데 감사합니다!! CalendarViewDelegate의 calendarScrollSender 프로퍼티를 weak으로 정의하여 해결할 예정입니다. 해당 리뷰는 Delegate 객체를 수정해야 되기에 새로운 PR에서 진행하여도 괜찮을까요?

확인했습니다!
PR 진행 후 멘션 주시면 함께 확인하겠습니다 :)

2024-06-13 11:49 UTC, noah0316 approved these changes
다음 PR에서 언급되었던 리뷰들 해결되면 멘션 부탁드릴게요~!

2024-06-14 03:59 UTC, merged