RepeatOtherDaysView 수정
ToDo-Garden/ToDo-Garden pull request #222
Opened 2024-06-10 03:21 UTC by HG-SONG

## 💡 관련 이슈
- closed: #220 

## 🎉 변경 사항
- 레이아웃 충돌 해결 
- 리네임 
- String 값 Constant로 이동

## 📌 PR Point
- #188 PR에서 언급되었던 모든 피드백사항을 반영하였습니다. 
   - 원인 : 스택뷰 높이/너비 미설정 
- 시뮬레이터에서 실행시 layout warning이 뜨지 않는 것을 확인하였습니다. 
## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-06-10 04:38 UTC, wood0203 requested changes
고생 많으셨습니다.
Preview로 동작을 확인하면서 일부 수정 요청 드립니다.

### 1. 시간 지정 버튼을 두 번 터치시 Disabled 되는 문제
`p1`
시간 지정 버튼이 활성화 상태일 때 클릭하면     
PickerView를 띄워줄 수 있도록 별도의 동작을 추가할 수 있어야 합니다.

### 제안) 2. 매일 버튼 터치 동작
`p2`
매일 버튼이 활성화 상태일 때, 한 번 더 터치하면
시간 지정 버튼이 활성화된다면 사용자가 더 편할 것 같습니다.

- 반드시 추가해달라는 의미가 아니기에, 울버린의 생각은 어떠실지 궁금합니다

### Q) 상태 업데이트
사용자가 투두의 반복 범위를 설정해주었을 때는 
외부에서 상태를 업데이트하는 방법이 있을까요?

**예시**
1. 사용자가 투두의 반복 범위를 2024.05.10 ~ 2024.06.01로 설정했을 때 
-> 시간 지정 버튼을 활성화 상태로 업데이트
2. 사용자가 투두를 매일 반복하도록 설정했을 때 
-> 매일 버튼을 선택된 상태로 업데이트


## 동작 화면
<img width="200" src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/b55685ee-d533-44e8-9c32-c2ed3922dfb0">

2024-06-10 04:38 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/DateButtonSet.swift
> +        innerStackView.heightAnchor.constraint(lessThanOrEqualTo: self.stackView.heightAnchor, multiplier: 0.5)
`p2`

multiplier 값도 Constant에 있으면 좋을 것 같습니다

2024-06-10 08:24 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/DateButtonSet.swift
> +        innerStackView.heightAnchor.constraint(lessThanOrEqualTo: self.stackView.heightAnchor, multiplier: 0.5)
@wood0203 

> 1. 시간 지정 버튼을 두 번 터치시 Disabled 되는 문제

회색버튼이 disabled상태가 아님을 먼저 알립니다. 회색버튼도 enable상태이며 터치 및 이벤트 전달이 가능한 상태입니다. 단지 날짜가 Selected되지 않은 상태입니다. 

______
이 문제를 해결하기 위한 주요 변경사항은, 
### LightRoundRectButton의 토글기능을 제거하였습니다. 
이제는 단순 터치만으로는 Selected상태를 변경할 수 없고, 
caller가 응답에 따라 조건체크를 한 뒤, repeatOtherDaysView.updateDateButtonState() 로 버튼의 불을 켜고 끌 수 있습니다.

____

(Unselected) 시간지정 버튼 터치 -> PikcerView 소환 -> 요청 및 응답 정상 체크 -> 초록불 들어옴(Selected) 의 흐름을 생각했습니다. 다만 컴포넌트 단위 개발에서 `PikcerView 소환 -> 요청 및 응답 정상 체크` 이 두 단계를 넣을 수는 없었습니다. 하지만 두 단계를 Caller가 설정할 수 있게 해놓았습니다. 

`pickerView 소환` : dateButtonSet는 public객체이며, UIButton과 똑같이 쓰일 수 있습니다. addAction,Target, isSelected등 활용가능합니다. 

```swift
#if DEBUG
@available(iOS 17.0, *)
#Preview {
  let repeatOtherDaysView = RepeatOtherDaysView(startDate: nil, endDate: nil)
  
  repeatOtherDaysView.dateButtonSet.addAction(UIAction{
    _ in 
    // pickerView 소환 코드 
  }, for: .touchUpInside)
  
  return repeatOtherDaysView
}
#endif
```
----
`요청 및 응답 정상 체크` : 이 부분은 아직 요청 , 응답 명세가 나오지 않았습니다. 다만 이 또한 isSelected 프로퍼티를 Caller가 조작할 수 있습니다. 
아래조건은 DatePickerView의 요청이 성공 / 실패 일때를 isSuccess 로 표현합니다. 

```swift
  let isSuccess = true
  
  repeatOtherDaysView.dateButtonSet.addAction(
    UIAction { _ in
    if isSuccess {
      repeatOtherDaysView.updateDateButtonState(isSelected: isSuccess)
       // 날짜 설정에 성공 ,실패 유무에 따라  Selected 상태 업데이트
      repeatOtherDaysView.updateDate(startDate: "1111.11.11", endDate: "2222.22.22")
       // 필요에 따라 날짜레이블도 업데이트 가능
    } else {
      repeatOtherDaysView.updateDateButtonState(isSelected: isSuccess)
       // 날짜 설정에 성공 ,실패 유무에 따라  Selected 상태 업데이트
    }
  },
  for: .touchUpInside)
```
PickerView에서 온 응답을 기반으로 위와 같이 updateDateButtonState를 Caller가 업데이트 할 수 있습니다. 

> Q) 상태 업데이트

- 초기화시 날짜가 지정되있다면 초기상태는 날짜지정에 불이 들어오는 상태로 표시됩니다.
- 초기화시 날짜가 지정되어있지 않다면 초기상태는 매일에 불이 들어오는 상태로 표시됩니다. 

++ 추가로 초기화 이후에도 아래 메서드로 상태변경이 가능합니다. 

-> `Date레이블 내용 업데이트` 는 아래 메서드로 외부에서 가능합니다. 필요에 따라 추상화시 인터페이스화 할 수 있습니다. 
```swift
repeatOtherDaysView.updateDate(startDate: "1111.11.11", endDate: "2222.22.22")
```

-> `Date레이블 Selected 업데이트` 는 아래 메서드로 외부에서 가능합니다. 필요에 따라 추상화시 인터페이스화 할 수 있습니다. 
```swift
repeatOtherDaysView.updateDateButtonState(isSelected: isSuccess)
```

> 제안) 2. 매일 버튼 터치 동작 

현재 구현상, 날짜지정 버튼에 토글 기능이 없어짐으로써 caller가 직접 날짜지정 버튼을 켜고 꺼야 합니다. 

1. Caller가 dateButtonsSet에 액션을 추가하여 DatePickerView를 소환한다.
2. DatePikcerView를 이용해서 어떤 요청을 보내고, 응답을 받는다. 
3. 응답이 성공이면 updateDateButtonState(isSelected: true) 로 날짜지정 버튼의 불을 켜준다. 
4. 응답이 실패면 updateDateButtonState(isSelected: false) 로 날짜지정 버튼의 불을 꺼준다. 

즉, 요청이 성공일때에만 수동으로 불을 켜야합니다. 
이 상황에서 매일버튼이 해제 되었을 때 불을 키게되면 이상하다고 생각합니다. 

하지만 우드가 "매일버튼이 해제 되었을 때 사용자에게 DatePickerView를 소환해주고 싶다. " 라고 한다면, 
그건 VIP 사이클 안에서 라우터가 해줘야 할 것 같습니다. 
그리고 그 후에 요청 성공,실패를 기반으로 불을 키고 끌 수 있는 것이죠.

2024-06-11 04:32 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/DateButtonSet.swift
> +        innerStackView.heightAnchor.constraint(lessThanOrEqualTo: self.stackView.heightAnchor, multiplier: 0.5)
자세한 설명 덕분에 이해가 잘 되었습니다. 감사합니다.

> 매일버튼이 해제 되었을 때 사용자에게 DatePickerView를 소환해주고 싶다.

맞습니다. 울버린이 말씀하신대로 라우터가 해주어야 하는게 맞다고 생각합니다.

제가 질문에 설명이 부족해 오해를 불러일으켰었네요
`버튼에 액션을 추가할 수 있는지` 여쭤보고자 했었습니다.
+ 해당 부분에 대해서도 자세하게 설명해주셔서 완벽하게 이해했습니다.

2024-06-11 04:35 UTC, wood0203 approved these changes

2024-06-11 04:36 UTC, merged