PostGroupScene(1): 의존성 주입 및 뷰 배치
ToDo-Garden/ToDo-Garden pull request #375
Opened 2024-07-23 08:07 UTC by HG-SONG

## 💡 관련 이슈
- closed: #370

## 🎉 변경 사항
- PostGroupScene(1): 의존성 주입 및 뷰 배치
  ->  페이로드를 제외하고, 파라미터로 전달받은 뷰객체들을 배치하였습니다. 
  
## 📌 PR Point
<img width="202" alt="스크린샷 2024-07-23 오후 4 46 53" src="https://github.com/user-attachments/assets/b27e4db6-99ee-4afe-88f7-8ef518bff46c">
<img width="198" alt="스크린샷 2024-07-23 오후 4 47 22" src="https://github.com/user-attachments/assets/e3ccde47-8279-43b9-b330-addd3ce3d88c">

- `>` 버튼을 터치하면, 색상을 선택할 수 있는 모달이 올라옵니다. 
   -> 다만, 인터랙터 미구현으로 인해 `완료`를 눌러도 적용되지 않습니다. 
   
- `TextInputView`와 `컬러선택` 이 둘 다 동시에 비어있지 않은 경우에만 `doneBottomButton`이 활성화 됩니다. 
   - `TextInputView`는 "" 이외에도 " ", "        " 와 같은 공백만 포함된 문자열에 대해서도 비어있다고 판단합니다. 
   - 즉, 지금 상태로는 `doneBottomButton`을 enable로 만들 수 없습니다. 
   
- 인터랙터 / 프레젠터 /  UseCase / Router 의 구현은 포함되어있지 않습니다. 다음 PR에서 확인하실 수 있을 듯 합니다.
- `TextInputView`를 터치했을 때 시뮬레이터 / 프리뷰 상에서 키보드가 안뜨는 이슈가 있습니다. 
- NavigationBar는 ManageGroupScene과 연결될 때 추가될 예정입니다. 

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-07-24 11:46 UTC, noah0316 requested changes
모듈간의 분리에 대해 신경을 많이쓰신 게 느껴져 좋았습니다!!
고생많으셨어요 :)

리뷰 확인 부탁드립니다!! 🙇‍♂️

2024-07-24 11:46 UTC, noah0316 commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +  private func isButtonEnabled() -> Bool {
`p3`

코드를 읽어보니 확인버튼의 활성화 여부를 확인하는 함수 같네요.
해당 컴포넌트가 어떤 컴포넌트인지 명시가 되어있으면 메소드명이 조금 더 명확해질 것 같아요 :)

2024-07-24 11:46 UTC, noah0316 commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +    if currentColor == UIColor.toDoGardenGrassNone {
`p3`

```swift
return currentColor == UIColor.toDoGardenGrassNone
```

이렇게 쓸 수 있을 것 같습니다 :)

2024-07-24 11:46 UTC, noah0316 commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +  private let textInputView: TextInputViewAPI
`p1`

이번 PR에 포함되어있지 않지만, 리뷰를 남깁니다.

해당 클래스를 상속할 필요가 없다면, 의미를 명확히하기 위해 `final` 키워드를 추가해주어도 좋을 것 같습니다 :)

2024-07-24 11:46 UTC, noah0316 commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +    if currentColor == UIColor.toDoGardenGrassNone {
`p1`

`UIColor.toDoGardenGrassNone`는 `ToDoGardenUIResource` 라이브러리에 명시되어있어 해당 라이브러리를 import 해주는게 좋을 것 같습니다:)

2024-07-24 11:46 UTC, noah0316 commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +        )
`p1`

`postGroupColorPickerRow`의 vertical position이 정해져있지 않아 오류가 발생할 것 같아 확인해보니 레이아웃 이슈가 있네요 지정해주면 좋을 것 같습니다!

|에러 메시지|
|---|
|<img width="480" alt="Screenshot 2024-07-24 at 8 25 24 PM" src="https://github.com/user-attachments/assets/95734634-4df8-4694-9972-83d091cf2aa9">|

2024-07-25 06:05 UTC, HG-SONG commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +  private func isButtonEnabled() -> Bool {
반영 완료 
> [13b8494](https://github.com/ToDo-Garden/ToDo-Garden/pull/375/commits/13b84941c6a43d805197e3fe31bf765723fe1d63)

2024-07-25 06:05 UTC, HG-SONG commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +    if currentColor == UIColor.toDoGardenGrassNone {
반영 완료 
> [78f8d90](https://github.com/ToDo-Garden/ToDo-Garden/pull/375/commits/78f8d9048025aae7f431a9bcf3c1eb0f5e6865bd)

2024-07-25 06:05 UTC, HG-SONG commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +  private let textInputView: TextInputViewAPI
반영 완료 
> [78f8d90](https://github.com/ToDo-Garden/ToDo-Garden/pull/375/commits/78f8d9048025aae7f431a9bcf3c1eb0f5e6865bd)

2024-07-25 06:05 UTC, HG-SONG commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +    if currentColor == UIColor.toDoGardenGrassNone {
반영 완료 
> [0fa7226](https://github.com/ToDo-Garden/ToDo-Garden/pull/375/commits/0fa72264c4df8313ec4b668e90082769c9f5903d)

2024-07-25 06:05 UTC, HG-SONG commented on ToDo-Garden/ToDo-Garden/PostGroupScene/Sources/PostGroupScene/PostGroupViewController.swift
> +        )
반영 완료 
postGroupColorPickerRow의 높이를 정의해주었습니다.
그러면서 forwardButton의 버티컬 포지션도 결정됩니다. 
> [b7c0f00](https://github.com/ToDo-Garden/ToDo-Garden/pull/375/commits/b7c0f0061dc0f21c1512b759650748c921957bd2)

2024-07-25 07:19 UTC, noah0316 approved these changes
확인했습니다 :)

현재는 완료 버튼의 활성화 여부와 관련된 로직, color가 선택되어있지 않은지 결정하는 사용자 입력에 대한 검증 로직이 VIP의 V에 있네요!

저도 이런 뷰와 매우 밀접하게 연관되어 있는 간단한 검증 로직은 View레이어에 있는게 좋은 것 같아요

하지만 만약 검증 로직이 함께 정의한 [스프레드 시트의 비즈니스 룰](https://docs.google.com/spreadsheets/d/17tg1z_x2UiSDCYD5yLnisMQkEVDgYIJNFICO8gTPkK4/edit?gid=1126544263#gid=1126544263&range=1:1)의 일부분이 되고, 다른 여러 곳에서 재사용되거나 복잡해진다면 Interactor로 이동하는 것도 괜찮은 방향일 것 같아요

코드 잘 봤습니다!!
고생하셨어요 🙌

2024-07-25 12:54 UTC, merged