NSMutableAttributedString 밑줄 생성 관련 Extension 추가
ToDo-Garden/ToDo-Garden pull request #40
Opened 2024-03-01 14:02 UTC by wood0203

## 💡 관련 이슈
- closed: #39 

## 🎉 변경 사항
- NSMutableAttributedText에서 지정한 범위에 원하는 색상의 밑줄을 생성하는 함수를 구현하였습니다.

## 📌 PR Point

- 디자인 요구사항인 모든 텍스트가 아닌 일부 텍스트에만 밑줄을 추가할 수 있도록 범위를 지정할 수 있게 구현하였습니다.

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-03-02 06:14 UTC, noah0316 requested changes

2024-03-02 06:14 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/NSMutableAttributedString+addUnderline.swift
> +      range: NSRange(location: location, length: length)
`location`과 `length`에 유효하지 않은 범위가 들어가는 것에 대한 대응이 필요할 것 같습니다 :)
`Out of bounds` 에러가 발생할 것 같아서요

2024-03-04 04:36 UTC, wood0203 commented
@noah0316
> `location`과 `length`에 유효하지 않은 범위가 들어가는 것에 대한 대응이 필요할 것 같습니다 :) `Out of bounds` 에러가 발생할 것 같아서요

피드백해주신 부분 반영하였습니다.
[e1d2c0b](https://github.com/ToDo-Garden/ToDo-Garden/pull/40/commits/e1d2c0b0d9652564f3e4f4fc7d765bcebff162ca)

2024-03-04 04:54 UTC, noah0316 approved these changes
확인했습니다 :)

2024-03-04 04:54 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/NSMutableAttributedString+addUnderline.swift
> +    let minimumLocation = 0
매직넘버 대신 상수 사용한 것 좋네요!

2024-03-04 04:54 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/NSMutableAttributedString+addUnderline.swift
> +  private func checkRangeToAddUnderlineIsValid(
(개인취향)
is 용법을 사용해도 좋았을 것 같네요!!

2024-03-04 05:06 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/NSMutableAttributedString+addUnderline.swift
> +  private func checkRangeToAddUnderlineIsValid(
예) https://developer.apple.com/documentation/foundation/timer/1408249-isvalid

2024-03-04 05:27 UTC, wood0203 commented
@noah0316 
> (개인취향) is 용법을 사용해도 좋았을 것 같네요!!

리뷰 해주신 부분 반영하였습니다.

2024-03-04 05:30 UTC, noah0316 commented
@wood0203 
> @noah0316
> 
> > (개인취향) is 용법을 사용해도 좋았을 것 같네요!!
> 
> 리뷰 해주신 부분 반영하였습니다.

확인했습니다! 고생하셨어요 :)

2024-03-04 05:32 UTC, wood0203 commented
@noah0316 
> @wood0203
> 
> > @noah0316
> > > (개인취향) is 용법을 사용해도 좋았을 것 같네요!!
> > 
> > 
> > 리뷰 해주신 부분 반영하였습니다.
> 
> 확인했습니다! 고생하셨어요 :)

감사합니다 머지하겠습니다!

2024-03-04 05:36 UTC, merged