Setting Scene에 필요한 이미지 추가
ToDo-Garden/ToDo-Garden pull request #407
Opened 2024-08-07 04:06 UTC by wood0203

## 💡 관련 이슈
- closed: #406 

## 🎉 변경 사항
- ToDoGardenUI 패키지에 설정 화면 UI 구현에 필요한 이미지들을 추가하였습니다.

## 📌 PR Point
추가한 이미지들은 다음과 같습니다.
- 이미지 추가 작업이라 FileChanged 수가 많습니다
1. 투두가든 로고 이미지: 이용 가이드 버튼에 사용
2. 나뭇잎 이미지: 버전 정보 표시 뷰에 사용
3. 프로필 기본 이미지: 설정 화면에서 프로필 기본 이미지에 사용

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-08-07 14:37 UTC, noah0316 requested changes

2024-08-07 14:37 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIResource/Assets.xcassets/defaultSettingProfileImage.imageset/default_setting_profile_image@3x.png
`p1`

설정화면 기본 프로필 이미지는 공유화면과 맞춰야할 것 같아요~!
해당 이미지는 프로필이 설정된 이미지 예시인 것 같습니다 :)

2024-08-08 02:26 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIResource/Assets.xcassets/defaultSettingProfileImage.imageset/default_setting_profile_image@3x.png
> `p1`
> 
> 설정화면 기본 프로필 이미지는 공유화면과 맞춰야할 것 같아요~! 해당 이미지는 프로필이 설정된 이미지 예시인 것 같습니다 :)

@noah0316
다음 커밋에서 반영하였습니다!
https://github.com/ToDo-Garden/ToDo-Garden/pull/407/commits/8d24332c387e14e7d2306049723e2de805557c56

2024-08-08 03:27 UTC, noah0316 approved these changes
확인했습니다:)

고생하셨어요!! Setting Scene 화이팅!!💪

2024-08-08 03:38 UTC, wood0203 commented
> 확인했습니다:)
> 
> 고생하셨어요!! Setting Scene 화이팅!!💪

감사합니다 머지하겠습니다!!
파이팅 🏃🏻‍♂️

2024-08-08 03:39 UTC, merged