ToDoGardenSwitch 추가
ToDo-Garden/ToDo-Garden pull request #41
Opened 2024-03-05 05:49 UTC by HG-SONG

## 💡 관련 이슈
- closed: #19 
## 🎉 변경 사항
- UISwitch의 extension을 통해 ToDoGardenSwitch 를 사용할 수 있습니다.
## 📌 PR Point
- isOn 파라미터를 통해 초기상태(On/Off)를 결정할 수 있습니다. 
``` swift
let switch = UISwitch()
switch.ToDoGardenSwitchStyle(isOn:false)
```
- 아래와 같이 표시됩니다.

![Simulator Screen Recording - iPhone 15 Pro - 2024-03-05 at 14 32 12](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/2f4b1226-9d75-4188-a841-b291e123d5b6)

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-03-05 06:06 UTC, wood0203 reviewed
수고많으셨습니다.
다음 리뷰들을 확인해주세요

2024-03-05 06:06 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.subviews.first?.subviews.first?.backgroundColor = UIColor.toDoGardenGreenGray
옵셔널 체이닝 과정에 nil이 발생하면 색상 적용이 안될 가능성이 있어 보입니다.
어떻게 생각하시나요?

2024-03-05 06:52 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.subviews.first?.subviews.first?.backgroundColor = UIColor.toDoGardenGreenGray
내부 구조를 건드린 customView가 아니라 UISwitch의 extension을 이용한 것이기 때문에, 초기화된 UISwitch의 뷰 계층 구조에서 해당 옵셔널이 가리키는 View가 nil일 가능성은 없다고 생각합니다. 
![스크린샷 2024-03-05 오후 3 40 08](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/58a09060-ab24-49c2-8056-870756f99ba1)

그럼에도 불구하고 나름 안정성을 고려하여 "?"를 사용하여 체이닝 했습니다.

2024-03-06 05:59 UTC, noah0316 requested changes

2024-03-06 05:59 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +import UIKit.UISwitch
팀 [코드 컨벤션](https://www.notion.so/806d4f6c76414f009533f39d5ea3c4ec?pvs=4#65587a1e5ac84af99ea380a2a20c97c5)을 참고해주세요!!

2024-03-06 05:59 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.subviews.first?.subviews.first?.backgroundColor = UIColor.toDoGardenGreenGray
```suggestion
    let view = self.subviews.first?.subviews.first
    view?.backgroundColor = UIColor.toDoGardenGreenGray
```

이런식으로 상수에 할당해주면 의미가 조금 더 명확해질 것 같아요 :)

2024-03-06 05:59 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.subviews.first?.subviews.first?.backgroundColor = UIColor.toDoGardenGreenGray
+ 앱이 백그라운드 상태에 들어갔다가 다시 돌아오는 경우 해당 색이 잘 반영이 되지 않네요 확인 부탁드립니다!

![Simulator Screen Recording - iPhone 15 Pro - 2024-03-06 at 14 57 29](https://github.com/ToDo-Garden/ToDo-Garden/assets/63908856/cb9c7bc3-d83f-400b-83b7-68f35d509824)

2024-03-06 08:12 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.subviews.first?.subviews.first?.backgroundColor = UIColor.toDoGardenGreenGray
- 해당 버그 수정하였습니다 ! 

> [8d462a8](https://github.com/ToDo-Garden/ToDo-Garden/pull/41/commits/8d462a8c18965f3b0c554379a18076c0e3cb889a)

백그라운드에서 포그라운드로 복귀하면, UISwitch의 subview들이 새롭게 대체되는 현상을 발견하였습니다. 

![스크린샷 2024-03-06 오후 5 02 52](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/662cdda3-21ee-40fd-b175-801a08458292)
![스크린샷 2024-03-06 오후 5 03 21](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/63335289-3316-4e2d-8abf-4f9fe17a6ba2)
(전 , 후의 주소값이 다름) 
즉, 전과 후의 스위치의 배경을 담당하는 UIView는 다른 객체입니다. 

백그라운드에서 포그라운드로 진입시 , subview 들이 새롭게 대체된다면, UISwitch의 layoutSubview()가 호출될 것이라고 판단하여 layoutSubview()를 오버라이딩 하기위해 Extension에서 Class로 재정의 하였습니다.  

아래는 결과 화면이며, 이제 해당 오류현상이 발생하지 않습니다.
![Simulator Screen Recording - iPhone 15 Pro - 2024-03-06 at 17 10 21](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/f31ff87f-c90d-464f-a0e3-3546b08f3048)

2024-03-06 08:17 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +import UIKit.UISwitch
해당내용 수정하였습니다.
> [8d462a8](https://github.com/ToDo-Garden/ToDo-Garden/pull/41/commits/8d462a8c18965f3b0c554379a18076c0e3cb889a)

2024-03-06 08:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.subviews.first?.subviews.first?.backgroundColor = UIColor.toDoGardenGreenGray
@HG-SONG 
내용 확인했습니다:)

2024-03-06 08:22 UTC, noah0316 requested changes
아래의 리뷰를 확인해주세요 :)

2024-03-06 08:22 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +//  UISwitch+ToDoGardenSwitch.swift
```suggestion
//  ToDoGardenSwitch.swift
```
`Class`로 재정의 해주신 것 확인했습니다! 파일명이 바뀌어야하지않을까요?

2024-03-06 08:22 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.setupOffTintColor()
함수의 추상화단계를 맞추는게 좋아보입니다!

2024-03-06 08:22 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.setupOffTintColor()
`layoutSubViews`에서 호출해준다면 init에서도 호출할 경우 `setupOffTintColor()` 메서드를 2번 호출해주는 것이 아닐까요?

2024-03-06 08:22 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    let offBackgroundView = self.subviews.first?.subviews.first
의미가 더 명확해졌네요👍

2024-03-06 08:27 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.setupOffTintColor()
혹은 `convenience init`을 사용해도 좋을 것 같네요 :)

2024-03-06 08:48 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.setupOffTintColor()
인정.
>[53c20d9](https://github.com/ToDo-Garden/ToDo-Garden/pull/41/commits/53c20d9b130a9d667e1fe8059d8215e5fdb330e9)

2024-03-06 08:48 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +    self.setupOffTintColor()
작업 완료 
> [17188bb](https://github.com/ToDo-Garden/ToDo-Garden/pull/41/commits/17188bb251526a50ae84f25a895337c9803398ba)

2024-03-06 08:48 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UISwitch+ToDoGardenSwitch.swift
> +//  UISwitch+ToDoGardenSwitch.swift
변경완료 하였습니다 
>[2c1a37a](https://github.com/ToDo-Garden/ToDo-Garden/pull/41/commits/2c1a37a9b9e77ea83d8ebddcc4427197ed89a835)

2024-03-06 08:50 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenSwitch.swift
> +  required init?(coder: NSCoder) {
해당 생성자에 따로 public 키워드를 달아주시지 않은 이유가 있을까요?

2024-03-06 08:54 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenSwitch.swift
> +  required init?(coder: NSCoder) {
@noah0316  수정완료
>[5ba3f8e](https://github.com/ToDo-Garden/ToDo-Garden/pull/41/commits/5ba3f8ecceebbc5220b62e14ca85bce0b09e185a)

2024-03-06 08:56 UTC, noah0316 approved these changes
수정사항 확인 했습니다 :)
고생하셨습니다!! 👍

2024-03-06 08:56 UTC, merged