AddButton 추가
ToDo-Garden/ToDo-Garden pull request #42
Opened 2024-03-05 06:45 UTC by wood0203

## 💡 관련 이슈
- closed: #38

## 🎉 변경 사항
- 그룹 및 리마인더를 추가하는 버튼인 **AddButton**을 추가하였습니다.
- 버튼의 스타일을 적용하는  **AddButtonSTyle**타입을 분리하였습니다.
- 버튼이 눌렸을 때 사용자가 인식할 수 있도록 색상의 alpha값을 낮추도록 설정하였습니다.

## 📌 PR Point
<img src="https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/d7f20fa0-8e56-4a14-af7b-8098354d9e0f" width="230" height="500">

## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-03-05 07:51 UTC, HG-SONG reviewed
리뷰 완료. 고생하셨소.

2024-03-05 07:51 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +        let alphaWhenHighlighted: CGFloat = 0.5
* 0.5가 반복적으로 쓰이는 부분이 있네요. 재사용가능하게 구성하는건 어떤가요 ?

* 그리고 0.5는 너무 투명하지 않은가요?

2024-03-07 05:31 UTC, noah0316 requested changes

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +import UIKit.UIButton
팀 [코드 컨벤션](https://www.notion.so/806d4f6c76414f009533f39d5ea3c4ec?pvs=4#65587a1e5ac84af99ea380a2a20c97c5)을 참고해주세요!!

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  public func addButtonStyle(with title: String) {
`add`라는 동사로 읽히게 되는 모호함이 있는 것 같은데 어떻게 생각하시나요?

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +    else { return }
팀 [코드 컨벤션](https://www.notion.so/806d4f6c76414f009533f39d5ea3c4ec?pvs=4#61c8fad9bc524c9e8581e0f46b689bce)을 참고해주세요 :)

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +    else { return }
팀 [코드 컨벤션](https://www.notion.so/806d4f6c76414f009533f39d5ea3c4ec?pvs=4#61c8fad9bc524c9e8581e0f46b689bce)을 참고해주세요 :)

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +    self.setupUIAppearance(with: title)
이곳에서 `AddButtonStyle.apply(for:,with:)`를 호출해주는건 어떻게 생각하실까요?
그렇게되면 12번 라인의 함수명도 `applyAddButtonStyle(with:)`와 같이 사용할 수 있을 것 같아서요

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  }
```suggestion
  fileprivate static func apply(
    for button: UIButton,
    with title: String
  ) {
    AddButtonStyle.applyConfiguration(
      for: button,
      with: UIButton.Configuration.plain()
    )
    AddButtonStyle.configureImage(for: button)
    AddButtonStyle.setImage(for: button)
    AddButtonStyle.setupTintColorWhenStateChanged(for: button)
    AddButtonStyle.setupTitle(for: button, with: title)
  }
}

extension AddButtonStyle {
private static func applyConfiguration(
  for button: UIButton,
  with configuration: UIButton.Configuration
) {
  button.configuration = configuration
}
	
private static func configureImage(for button: UIButton) {
  let imagePadding: CGFloat = 4.0
  button.configuration?.imagePadding = imagePadding
  button.configuration?.imagePlacement = NSDirectionalRectEdge.leading
}
	
private static func setImage(for button: UIButton) {
  let renderingMode = UIImage.RenderingMode.alwaysTemplate
  let addButtonImage = UIImage.addButton.withRenderingMode(renderingMode)
  button.setImage(addButtonImage, for: .normal)
}

```

위 코드처럼 하나의 함수가 하나의 일만 하도록 분리해보는건 어떨까요?

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  private static func convertAttributedTitle(
새로운 `NSMutableAttributedString`객체를 생성하고 있는데, `convert` 대신 `make`라는 접두사를 붙이는건 어떨까요?

2024-03-07 05:31 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  private static func convertAttributedTitle(
해당 함수도 나눠볼 수 있을 것 같아요!

2024-03-07 07:22 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +        let alphaWhenHighlighted: CGFloat = 0.5
@HG-SONG Alpha 값을 0.7로 수정해보았는데 괜찮은지 확인 부탁드립니다!
|Alpha=0.5|Alpha=0.7|
|---|---|
|![Simulator Screen Recording - iPhone 15 - 2024-03-07 at 16 16 32](https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/e45de411-6909-402d-8c84-fb7d4ffa7916)|![Simulator Screen Recording - iPhone 15 - 2024-03-07 at 16 17 54](https://github.com/ToDo-Garden/ToDo-Garden/assets/84387335/a7cf369d-49ea-4632-8482-a9fe9b854d2e)|

2024-03-07 07:23 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +        let alphaWhenHighlighted: CGFloat = 0.5
추가로 alpha 값을 재사용하도록 ToDoGardenUIComponent 모듈에 선언할 예정인데,
해당 변경사항은 새로운 브랜치를 생성하여 진행해도 괜찮을까요?

2024-03-07 07:28 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +import UIKit.UIButton
@noah0316 
반영하였습니다!
> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/268de65293d4002b11d210295fd1c183260c1bfd

2024-03-07 07:29 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  public func addButtonStyle(with title: String) {
감사합니다 저도 모호하다 싶어 apply로 prefix를 변경해보았습니다!
> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/bb6a94acc563d59717067f48daa5fe3ab77dfd74

2024-03-07 07:29 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +    else { return }
반영하였습니다
> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/25e04ae3ca5704396065c4600c99a2fabdf4b2e5

2024-03-07 07:30 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +        let alphaWhenHighlighted: CGFloat = 0.5
- 0.7이 되니까 제 눈에는 더 보기 좋네용 

- 넵 재사용 관련 내용 인지했습니다.

2024-03-07 07:30 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +    else { return }
반영하였습니다!
> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/44de18e0d1667a99eab9b70411e7c121bfc148ee

2024-03-07 07:31 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +    self.setupUIAppearance(with: title)
넵 setupUIAppearance 메서드를 삭제하고 직접 apply 함수를 호출하도록 반영해보았습니다!
> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/c86277b432bbb5af7736d232c8d99afdf08a2c0d

2024-03-07 07:32 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  }
직접 코드까지.. 정말 감사합니다!! 단계를 나눠서 반영해보았습니다
> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/c86277b432bbb5af7736d232c8d99afdf08a2c0d

2024-03-07 07:33 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  private static func convertAttributedTitle(
prefix를 make로 수정하였습니다
> 새로운 `NSMutableAttributedString`객체를 생성하고 있는데, `convert` 대신 `make`라는 접두사를 붙이는건 어떨까요?
> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/36fe2e3997d2aa065aef30c6144f36694a69fb80

2024-03-07 07:35 UTC, wood0203 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/UIButton+AddButton.swift
> +  private static func convertAttributedTitle(
타이틀 생성 함수와 언더라인 추가 함수로 분리해보았습니다!  확인 부탁드립니다!

> 해당 함수도 나눠볼 수 있을 것 같아요!

> https://github.com/ToDo-Garden/ToDo-Garden/pull/42/commits/c166eef1513a215ae944bbcd51697868e86bdbbd

2024-03-07 08:01 UTC, HG-SONG approved these changes

2024-03-07 10:45 UTC, noah0316 approved these changes
고생하셨습니다!!! 👍

2024-03-07 10:47 UTC, wood0203 commented
감사합니다 머지하도록 하겠습니다!

2024-03-07 10:48 UTC, merged