ToDoGardenBoxButtonConstant 추가
ToDo-Garden/ToDo-Garden pull request #52
Opened 2024-03-21 07:01 UTC by HG-SONG

## 💡 관련 이슈
- #49 
## 🎉 변경 사항
- ToDoGardenUIConstant에 ToDoGardenBoxButtonConstant를 추가합니다. 
## 📌 PR Point
- ToDoGardenBoxButton에 필요한 Constant들을 정의하였습니다. 
- 아래와 같이 사용가능합니다.

```swift
    Constant.ToDoGardenBoxButton.Alpha.highlighted
    Constant.ToDoGardenBoxButton.Size.primary.width
```
## 📝 셀프체크리스트

- [x]  머지하려고 하는 브랜치가 올바른가?
- [x]  코딩컨벤션을 준수하는가?
- [x]  PR과 관련없는 변경사항이 없는가?
- [ ]  변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ]  새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

2024-03-21 07:37 UTC, noah0316 requested changes

2024-03-21 07:37 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +import CoreGraphics
참고)
CGFloat은 Foundation내부로 들어오게 되었습니다.

https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/CGFloat.swift

2024-03-21 07:37 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +        return 302.0
primary의 값이(302.0)이 바뀌게 된다면 아래의 enum들의 302.0과 연관된 매직넘버들이 모두 수정되어야할 것 같은데 어떻게 생각하시나요?

수정 및 변경으로 인한 영향이 최소화되면 좋을 것 같아요

2024-03-21 07:37 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +        return 49.0 / 2
모든 케이스에 대해 같은 동작을 하고 있습니다.
computed property를 이용하셨다면, 한번만 계산하는 로직으로 작성할 수 있지 않을까요?🧐

2024-03-21 07:37 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +        return 302.0
아래 라인에서 등장하는 모든 매직넘버 역시 동일합니다.

2024-03-22 05:34 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +import CoreGraphics
수정완료. 

>[6af0afe](https://github.com/ToDo-Garden/ToDo-Garden/pull/52/commits/6af0afe01dac0dbec51a65a4ffc6a32b0fe0721b)

2024-03-22 05:34 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +        return 302.0
switch가 포함된 부분을 제거하고 , static 상수로 선언하는 방식으로 수정해보았습니다. 
PR본문 내용과 같이, 사용하는 쪽에서도 똑같이 접근하여 사용할 수 있으며, 직관적으로 무슨 내용인지 알 수 있습니다. 무엇보다도 코드의 양이 확 줄어서 보기 편할 것 같다는 생각입니다.

>[73d6991](https://github.com/ToDo-Garden/ToDo-Garden/pull/52/commits/73d6991177d1558337bd9a3e713cf3c79042a833)

2024-03-22 05:34 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +        return 49.0 / 2
height를 이용해서 사용할 수 있는 값이므로 해당내용을 제거하였습니다.

2024-03-22 05:35 UTC, HG-SONG reviewed
@noah0316 피드백 반영 사항 확인 부탁드릴게용 ~^^

2024-03-22 05:53 UTC, noah0316 approved these changes
훨씬 변경에 용이해진 것같아요!! 고생하셨습니다!!

2024-03-22 05:53 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +    public static let tertiary = CGSize(width: 288.0, height: 49.0)
Alpha 내부의 상수들은 타입 명시가 되어있고, Size 내부의 상수들은 타입 명시가 안되어있는데 어떤 의도일까요~?!

2024-03-22 06:11 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIConstant/Constant+ToDoGardenBoxButton.swift
> +    public static let tertiary = CGSize(width: 288.0, height: 49.0)
헉. 수정하였습니다 

>[f97aee1](https://github.com/ToDo-Garden/ToDo-Garden/pull/52/commits/f97aee102012f73249cb8d39f81108d9d72a3060)

2024-03-22 06:12 UTC, wood0203 approved these changes
확인했습니다

2024-03-22 06:16 UTC, merged