ToDoGardenBoxButton 추가
ToDo-Garden/ToDo-Garden pull request #54
Opened 2024-03-22 07:08 UTC by HG-SONG

## 💡 관련 이슈
- #43 

## 🎉 변경 사항

- ToDoGardenBoxButton 구현 
   - 3가지 Size를 설정할 수 있습니다.
   - enable/disable 상태 변경이 가능합니다.
   - 터치에 대한 highlight 효과

- 필요한 constant를 ToDoGardenBoxButtonConstant에 정의하였습니다.

## 📌 PR Point

- ToDoButtonBoxButton 클래스로 아래와 같은  버튼들을 표시할 수 있습니다. 

![Simulator Screen Recording - iPhone 15 Pro - 2024-03-20 at 18 41 05](https://github.com/ToDo-Garden/ToDo-Garden/assets/88966578/9f12c467-7f31-4c02-81e5-d8de45f89de2)
** 하이라이트 효과의 경우 disable에선 작동하지 않습니다.

- 인스턴스 생성시 , 어떤 종류의 버튼인지 알 수 있도록 init()을 구성하였습니다.
```swift
init(
    isRoundRect: Bool, // roundRect 여부
    text: String, // 버튼에 들어갈 text
    sizeType: CGSize // 버튼 size 
  )
```

2024-04-01 05:18 UTC, noah0316 requested changes

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    enable()
`self` 키워드가 누락된 것 같네요 👀

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    enable()
self 키워드가 누락된 것 같네요 👀

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    enable()
초기화 시점에서 버튼의 상태를 항상 enable로 정해주게되면, disable 상태로 버튼을 만들기 위해서 disable 함수를 호출해야하지 않나요?

버튼을 유연하게 생성하기 위해 생성자에서 고정된 상태를 정해주는 것보다, 생성자의 파라미터로 isEnabled를 받는것도 좋아보입니다.

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    sizeType: CGSize
ToDoGardenBoxButton을 사용하기 위해선 3가지의 타입이 다 있어야하나요?

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    sizeType: CGSize
PR 본문에는 
`3가지 Size를 설정할 수 있습니다.`
라고 되어있는데 `CGSize`를 파라미터로 받는다면 어떤 Size든 생성 가능한 것 아닐까요?

PR 본문에서 언급하신 `Primary`라는 사이즈에 대한 정의를 찾아보려했지만 생성자에선 찾아볼 수 없어서 코멘트 남깁니다.

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +// private method
컨벤션을 지켜주세요 :)
`// MARK: -`

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    _ size: CGSize
setup을 사용할 때 호출하는 쪽에서는 

```swift
self.setup(false, "sdf", CGSize(width: 100, height: 100)
```
과 같이 사용할 수도 있을 것 같은데 파라미터에 대한 맥락이 조금 더 필요하지 않을까요?

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    if isRoundRect {
해당 함수를 호출하기 이전에 속성에 대한 검사를 한 후 호출해주는게 좋지 않을까요?
해당 속성도 early exit이 가능할 것 같은데 함수 내부에서 두번 검사를 하는 것은 SRP 관점에서 좋지 않아보입니다!

2024-04-01 05:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +  private func setupFont() {
title과 관련된 단어가 함수명에 들어가도 좋을 것 같네요

2024-04-01 08:03 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    enable()
동의합니다. 해당 사항 변경하였습니다. 
이제 파라미터로 받은 뒤, 초기화 메소드 내부에서 isEnabled를 세팅합니다.
> [d2dc35f](https://github.com/ToDo-Garden/ToDo-Garden/pull/54/commits/d2dc35f7f093fd4c4150271f3b8b61edbad1b7b1)

2024-04-01 08:03 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    sizeType: CGSize
1) 먼저 ToDoGardenBoxButton를 사용하기 위해서는 3가지 타입이 필요한 것이 맞습니다. ToDoGardenBoxButton 하나의 컴포넌트를 이용해서 유사하지만 조금씩 다른 타입의 버튼을 표시하기 위한 의도입니다. 

2) 본문에 기재된 `3가지 Size를 설정할 수 있습니다.`보다는 `여러가지 Size를 설정할 수 있습니다.` 가 더 맞는 표현인 것 같습니다. Constant에서 전달받는 Size는 아래와 같이 정의되어 있습니다. 
```swift
extension Constant.ToDoGardenBoxButton {
  public enum Alpha {
    public static let normal: CGFloat = 1.0
    public static let highlighted: CGFloat = 0.7
  }
  
  public enum Size {
    public static let primary: CGSize = CGSize(width: 302.0, height: 49.0)
    public static let secondary: CGSize = CGSize(width: 287.0, height: 55.0)
    public static let tertiary: CGSize = CGSize(width: 288.0, height: 49.0)
  }
}
```

CGSize를 파라미터로 받는 이유는 위와 같은 방법(enum - static 상수)로 정의되어 있기 때문입니다. 만약 위와 같은 방법이 아닌 enum - case 방식으로 정의를 한다면 파라미터 타입을 Constant.ToDoGardenBoxButton.Size 로 제한하여 3가지 크기에 대해서만 다룰 수 있겠지만, 혹시 모를 확장의 가능성을 염두한 부분도 있고, 조건 분기에 대한 복잡함이 추가될 것 같아서 해당 파라미터는 CGSize로 받기로 하였습니다.

2024-04-01 08:03 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +// private method
수정 완료 
> [89c21f9](https://github.com/ToDo-Garden/ToDo-Garden/pull/54/commits/89c21f9766ae7c74ef929b885a809da1a367f87c)

2024-04-01 08:03 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    if isRoundRect {
중복 검사 로직을 제거하였습니다. 또한, 이제는 isRoundRect 속성을 가지고 있지 않고, 초기화메소드에서 true/false를 체크 한 뒤 코너래디우스를 세팅하게끔 수정하였습니다. 
>[d7a78c5](https://github.com/ToDo-Garden/ToDo-Garden/pull/54/commits/d7a78c57a285b861bef488e4d2fe96fafd848693)

2024-04-01 08:03 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    _ size: CGSize
"_" 를 제거하여 이젠 파라미터를 생략하지 않습니다. 물 흐르듯 한문장으로 읽히는 구조는 아니지만, 각 파라미터의 역할이 무엇인지는 명확하게 알 수 있도록 수정하였습니다. 
> [52c3696](https://github.com/ToDo-Garden/ToDo-Garden/pull/54/commits/52c369662606c5bec169a45c6cc4266f3d7cb42c)

2024-04-01 08:03 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +  private func setupFont() {
setupFont() -> setupTitleFont() 로 수정하였습니다. 
> [343f6be](https://github.com/ToDo-Garden/ToDo-Garden/pull/54/commits/343f6be64fa047f027f3268b7cfa03f849c4aedf)

2024-04-01 08:06 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    self.isEnabled = isEnabled
생성자에서 값을 할당해줄경우 property observer가 호출되지 않을텐데 이 부분에 대한 대응이 이루어져있을까요? 👀
[문서 링크](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization/#Setting-Initial-Values-for-Stored-Properties)

2024-04-01 08:17 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    sizeType: CGSize
> 1. 먼저 ToDoGardenBoxButton를 사용하기 위해서는 3가지 타입이 필요한 것이 맞습니다. ToDoGardenBoxButton 하나의 컴포넌트를 이용해서 유사하지만 조금씩 다른 타입의 버튼을 표시하기 위한 의도입니다.

1. 본문을 통해 해당 의도를 확인하였습니다. (하지만 아래에서는 그 의도가 불분명해지는 것 같습니다.)


> enum - case 방식으로 정의를 한다면 파라미터 타입을 Constant.ToDoGardenBoxButton.Size 로 제한하여 3가지 크기에 대해서만 다룰 수 있겠지만, 혹시 모를 확장의 가능성을 염두한 부분도 있고, 조건 분기에 대한 복잡함이 추가될 것 같아서 해당 파라미터는 CGSize로 받기로 하였습니다.

그렇다면 호출하는(혹은 사용하는)사람의 입장에서는 해당 Constant타입의 상수에 대한 맥락을 미리 알고 있어야하겠네요!
  a. 만약 파라미터 타입을 Constant.ToDoGardenBoxButton.Size 로 제한한다면 조건 분기에 대한 복잡함은 어떤식으로 생길 수 있을까요?

2024-04-03 05:47 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    sizeType: CGSize
```swift
public enum Size {
    case primary
    case secondary
    case tertiary

    var width: CGFloat {
        switch self {
        case .primary:
            return 302.0
        case .secondary:
            return 287.0
        case .tertiary:
            return 288.0
        }
     }

    var height: CGFloat {
        switch self {
        case .primary,.tertiary:
            return 49.0
        case .secondary:
            return 55.0
        }
    }
}
```
조건분기에 대한 복잡함이 큰 편은 아닙니다만, 위와 같은 맥락으로 구현이 될 것 같습니다. 
이런식으로 Size 내부에 case별 분기를 정의한다면 , 아래 코드처럼 파라미터의 타입을 변경할 수 있습니다. 이렇게 되면 CGSize(width:100,height:200)과 같은 임의의 크기(Size에 정의되어 있지 않은 크기)는 부여할 수 없고, 호출하는 쪽에서는 Constant에 대한 맥락을 모르더라도, 자동완성으로 enum에 대한 case가 뜨기 때문에 사용할 때는 편할 수 있다는 장점이 있습니다.

```swift
public convenience init(
    isRoundRect: Bool,
    text: String,
    size: Constant.ToDoGardenBoxButton.Size, // CGSize를 받지 않아도 됨
    isEnabled: Bool
  ) {
  ...
}
```

반면, 기존의 코드가 더 간결하고 직관적일 수 있겠습니다. 혹시라도 새로운 크기를 고려해야할 때에 수정사항을 최소화할 수 있는 장점도 있겠습니다. 또한, Constant에 정의해놓은 Size가 CGSize로 제공이 되고 있지만, 이런 맥락을 모를 때에는 의도한 Size 이외의 다른 CGSize가 파라미터로 입력될 수 있습니다.

두 방법중 선택을 한다고 하면, 저는 기존의 방법을 선택하고 싶습니다.

2024-04-03 06:18 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    sizeType: CGSize
설명 감사합니다!
변경 및 수정에는 말씀주신 방법이 더 용이할 것 같네요!! 글을 통해 의도를 더 잘 알 수 있었어요 🙇‍♂️

> 두 방법중 선택을 한다고 하면, 저는 기존의 방법을 선택하고 싶습니다.

기존의 방법으로 가시죠!

2024-04-03 06:48 UTC, HG-SONG commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    self.isEnabled = isEnabled
해당 문제점을 보완하기 위해 생성시, 최초 1회 isEnabled에 따라 배경색을 수동으로 적용시켰습니다. 
생성 이후에 일어나는 isEnabled의 변화에 따른 대응은 프로퍼티 옵저버를 이용합니다. 
>[455a637](https://github.com/ToDo-Garden/ToDo-Garden/pull/54/commits/455a637c0b55cadffe3dc3b841060e4312e97cfb)

2024-04-03 07:42 UTC, noah0316 commented on ToDo-Garden/ToDoGardenUI/Sources/ToDoGardenUIComponent/ToDoGardenBoxButton.swift
> +    self.isEnabled = isEnabled
확인했습니다! 👍

2024-04-03 07:43 UTC, noah0316 approved these changes

2024-04-03 08:18 UTC, merged